#!/bin/bash

function initialize() {
    cat <<EOF

Cash Register v0.1

EOF
}

function show_help() {
    cat<<EOF

Items
  d  list by description
  i  list by item number
  p  list by price
Transactions
  [[-]#] ####  add +/- quantity
  s  show cart
  t  show total
  a  abort transaction
  f  finalize transaction
Other
  q  quit

EOF
}

function list_description() {
    awk 'BEGIN{ print "Code     Price  Description" }; { printf "%s%10s  %s\n",\
    $1, $2, $3 }' FS='\t' items.dat | (sed -u 1q; sort -k 3) | less
}

function list_number() {
    awk 'BEGIN{ print "Code     Price  Description" }; { printf "%s%10s  %s\n",\
    $1, $2, $3 }' FS='\t' items.dat | (sed -u 1q; sort -k 1) | less
}

function list_price() {
    awk 'BEGIN{ print "Code     Price  Description" }; { printf "%s%10s  %s\n",\
    $1, $2, $3 }' FS='\t' items.dat | (sed -u 1q; sort -k 2 -g) | less
}

function show_cart() {
    echo
    if [ ! -s .cart ]; then
	printf "Empty.\n"
    else
	awk '
	    BEGIN{ print "Quantity    Code     Price  Description" };
	    { printf "%8s%8s%10s  %s\n", $1, $2, $3, $4 }
	    ' FS='\t' .cart
    fi
    echo
}

function get_total() {
    local result=$(awk '{ total+=($1*$3) } END { print total }' .cart)
    echo $result
}

function show_total() {
    result=$(get_total)
    printf "\nTotal: %s\n\n" "$result"
}

function abort_transaction() {
    echo
    read -p 'Abort transaction (Yes/No)? ' selection

    while [ "$selection" != "No" ]
    do
	if [ "$selection" = "Yes" ];
	then
	    > .cart
	    echo
	    return 1
	fi
	read -p 'Abort transaction (Yes/No)? ' selection
    done
    echo
}

function finalize_transaction() {
    total=$(echo $(get_total) | cut -d':' -f2)
    printf "\n"

    if [ ! -s .cart ] || [ $(echo "$total == 0" | bc) == 1 ];
    then
        echo -e "Change: 0.00\n"
        return 0
    fi

    read -p "Enter payment ($total remaining, blank to abort): " payment

    # If payment is empty, exit program
    if [[ $payment = "" ]];
    then
        echo
        return 0
    fi

    if [ $(echo "$payment > $total" | bc) == 1 ];
    then
      total=$(echo "$payment - $total" | bc)
      printf "\nChange: $total\n\n"
      printf "Generating PDF...\n"
      printf "Displaying PDF...\n\n"
      generate_receipt
    else
      while [ $(echo "$total - $payment > 0" | bc) == 1 ];
      do
        total=$(echo "$total - $payment" | bc)
        read -p "Enter payment ($total remaining, blank to abort): " payment
      done

      if [ $(echo "$payment > $total" | bc) == 1 ];
      then
        total=$(echo "$payment - $total" | bc)
        printf "\nChange: $total\n\n"
        printf "Generating PDF...\n"
        printf "Displaying PDF...\n\n"
        generate_receipt
      elif [ $(echo "$payment == $total" | bc) == 1 ];
      then
        printf "\nChange: 0.00\n\n"
        printf "Generating PDF...\n"
        printf "Displaying PDF...\n\n"
        generate_receipt
      fi
    fi
}

function generate_receipt() {
  awk -F '\t' '
  {array[$2] += $1}
  {array2[$2] = $3}
  {array3[$2] = $4}
  END {
    for (i in array)
      printf "%s,%s,%s,%s\n", i, array3[i], array[i], array2[i]}
  ' .cart > .receipt

  awk -F',' '$3 != 0' .receipt > temp && mv temp .receipt
  sort -k1 -n -o .receipt{,}

  pdflatex receipt < /dev/null > /dev/null
  evince receipt.pdf
}

function add_cart() {
    if [ "$#" -eq 1 ];
    then
	line=$(awk -v pat="$1" '$0~pat' items.dat)
        read id price desc <<< $line
        printf "\nAdded 1 x %s @ %s each\n\n" "$desc" "$price"
        printf "1\t%s\t%s\t%s\n" "$1" "$price" "$desc" >> .cart
    elif [ "$#" -eq 2 ];
    then
	quantity=$1
	line=$(awk -v pat="$2" '$0~pat' items.dat)
	read id price desc <<< $line
	printf "\nAdded %s x %s @ %s each\n\n" "$quantity" "$desc" "$price"
	printf "%s\t%s\t%s\t%s\n" "$quantity" "$id" "$price" "$desc" >> .cart
    fi
}

function main() {
    initialize

    read -p 'Selection (h for help)? ' selection

    while [ "$selection" != q ]
    do
	case "$selection" in
	    h) show_help ;;
	    d) list_description ;;
	    i) list_number ;;
	    p) list_price ;;
	    s) show_cart ;;
	    t) show_total ;;
	    a) abort_transaction ;;
	    f) finalize_transaction ;;
	    q) exit 0 ;;
	    [-0-9]*) add_cart $selection ;;
	esac
	read -p 'Selection (h for help)? ' selection
    done
}

main "$@"
